### ISSUE TITLE
[Doc] Спецификация проекта

### ISSUE THREAD

**Issue by nphl** [nphl/DJP-algorithm#1]

**Comment by rosshkaa** [comment]
[Спецификация.docx](https://github.com/nphl/DJP-algorithm/files/335054/default.docx)

**Comment by rosshkaa** [comment]
[Спецификация.docx](https://github.com/nphl/DJP-algorithm/files/335474/default.docx)

**Comment by rosshkaa** [comment]
[Спецификация.docx](https://github.com/nphl/DJP-algorithm/files/335480/default.docx)
