### ISSUE TITLE
[FR] Создать GUI прототип проекта

### ISSUE THREAD

**Issue by nphl** [nphl/DJP-algorithm#3]

**Comment by rosshkaa** [comment]
![drawframe](https://cloud.githubusercontent.com/assets/17096579/16440125/9f68a100-3dc7-11e6-8a00-d4149fe28862.PNG)
![mainframe](https://cloud.githubusercontent.com/assets/17096579/16440126/9f807578-3dc7-11e6-85ff-e975329b46e4.PNG)
